export const GET_DATA_MUTATION = "GET_DATA_MUTATION";
export const GET_DATA_MUTATION_FAILED = "GET_DATA_MUTATION_FAILED";

export const GET_DETAIL_MUTATION = "GET_DETAIL_MUTATION";
export const GET_DETAIL_MUTATION_FAILED = "GET_DETAIL_MUTATION_FAILED";